# Generated by Django 5.1.5 on 2025-01-23 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhare_no', models.IntegerField(unique=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50, unique=True)),
                ('dep_description', models.CharField(max_length=50)),
                ('dep_Hod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ve_name', models.CharField(choices=[('Tata', 'Tata'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Hyundai', 'Hyundai'), ('Hounda', 'Hounda')], max_length=50)),
                ('ve_veriants', models.CharField(choices=[('Tata', 'Altra'), ('BMW', 'BMW X1'), ('Audi', 'Audi Q5'), ('Hyundai', 'verna'), ('Hounda', 'Ameze')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_father_name', models.CharField(max_length=50)),
                ('stu_DateOfBirth', models.DateField()),
                ('stu_Email', models.EmailField(max_length=254)),
                ('stu_RollNumber', models.CharField(max_length=20, unique=True)),
                ('stu_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', to_field='dep_name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Contect', models.IntegerField()),
                ('adhar_no', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.adhare')),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(choices=[('Petrol', 'Petrol'), ('Desal', 'Desal'), ('CNG', 'CNG')], max_length=50)),
                ('ve_name', models.ManyToManyField(to='app.vehicle')),
            ],
        ),
    ]
