# Generated by Django 5.1.5 on 2025-01-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userprofile_adhar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=20, unique=True)),
                ('dep_description', models.CharField(max_length=50)),
                ('dep_Hod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_father_name', models.CharField(max_length=50)),
                ('stu_DateOfBirth', models.DateField()),
                ('stu_Email', models.EmailField(max_length=254)),
                ('stu_RollNumber', models.CharField(max_length=20, unique=True)),
                ('stu_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department')),
            ],
        ),
    ]
