# Generated by Django 5.1.5 on 2025-01-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_department_dep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', to_field='dep_name'),
        ),
    ]
